service: sample-app
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-east-1
  memorySize: 128
functions:
  app:
    handler: index.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true